type: function
selector:
  computer:
    osName:
      - "Windows 11"
function:
  name: open_application
  description: Open an application on the computer.
  parameters:
    type: object
    properties:
      application_name:
        type: string
        description: The name of the application to open. Include the file extension (e.g., "notepad.exe").
    required:
      - application_name
  exec:
    language: kotlin